### ISSUE TITLE
Hello, is this project still being updated?

### ISSUE THREAD

**Issue by jackchang1025** [HelgeSverre/mindwave#12]
I found that the meta field will report an error, probably because meta is an array

![image](https://github.com/HelgeSverre/mindwave/assets/71494064/45b08fa7-c9dc-49cb-84de-96dd29b3f168)

![image](https://github.com/HelgeSverre/mindwave/assets/71494064/e7f2fa84-0d6e-44b8-935c-41f9cefc5fe7)

**Comment by HelgeSverre** [comment]
On which vectorstore driver does this occur?

**Comment by jackchang1025** [comment]
@HelgeSverre  pinecone

**Comment by HelgeSverre** [comment]
Sadly i have not had the time to add support for this, however as a temporary workaround, turn your metadata into json using `json_encode()` and `json_decode()` it when retrieving it.

**Comment by HelgeSverre** [comment]
@jackchang1025 forgot to @ you

**Comment by HelgeSverre** [comment]
@jackchang1025 starting back up now, will adress this issue in a future version.
