### ISSUE TITLE
How to use with data in mysql?

### ISSUE THREAD

**Issue by faizananwerali** [HelgeSverre/mindwave#14]
I have many tables in MySQL, now I want to search in it by asking a question in the chatbot. How do I implement automatically adding data from MySQL to this? so the questions can be answered in the chatbot on this data.

Like I have the users table and User Model, which has around 30 columns. Now when clients or admins question any information from the `users` table in the chatbot then it should be able to answer it.

similarly it should be able to answer about all the tables in the database.

**Comment by HelgeSverre** [comment]
Working on a new release where this usecase will be easier, but essentially, you can do this today by using a custom tool that takes a aearch query as input, and returns a csv list of results from your database based on the search query.
